export const columns = [
  { name: "NAME", uid: "name" },
  { name: "ROLE", uid: "role" },
  { name: "STATUS", uid: "status" },
  { name: "ACTIONS", uid: "actions" },
];

export const dtColumns = [
  { name: "Client Name", uid: "clientName" },
  { name: "Project Descriptions", uid: "projectDesc" },
  { name: "Date Received", uid: "dateReceived" },
  { name: "Sales Personnel", uid: "salesPersonnel" },
  { name: "System Diagram", uid: "systemDiagram" },
  { name: "Endorsed Date", uid: "eBoqDate" },
  { name: "Structural BOQ", uid: "structuralBoq" },
  { name: "Endorsed Date", uid: "sBoqDate" },
  { name: "Sir ME", uid: "sirME" },
  { name: "Sir MJ/Harold", uid: "sirMJH" },
  { name: "Status", uid: "status" },
  { name: "ACTIONS", uid: "actions" },
];

export const dtTasks = [
  {
    id: 1,
    clientName: "REV1 SM MARIKINA OUTDOOR",
    projectDesc: "OUTDOOR LED",
    dateReceived: "06/05/25",
    salesPersonnel: "MLB",
    systemDiagram: "M.GIGANTE",
    eBoqDate: "06/05/25",
    structuralBoq: "J.COLA",
    sBoqDate: "06/05/25",
    sirME: " - ",
    sirMJH: " - ",
    status: "WIP",
  },
  {
    id: 2,
    clientName: "SM MARIKINA INDOOR",
    projectDesc: "INDOOR LED",
    dateReceived: "06/05/25",
    salesPersonnel: "MLB",
    systemDiagram: "M.GIGANTE",
    eBoqDate: "06/05/25",
    structuralBoq: "J.ARDINEL",
    sBoqDate: "06/05/25",
    sirME: " - ",
    sirMJH: " - ",
    status: "WIP",
  },
  {
    id: 3,
    clientName: "MEDICAL HUBB",
    projectDesc: "INDOOR LED",
    dateReceived: "06/05/25",
    salesPersonnel: "KENNETH",
    systemDiagram: "M.GIGANTE",
    eBoqDate: "06/05/25",
    structuralBoq: " - ",
    sBoqDate: "06/05/25",
    sirME: " - ",
    sirMJH: " - ",
    status: "WIP",
  },
  {
    id: 4,
    clientName: "UPOU",
    projectDesc: "SEMI OUTDOOR LED",
    dateReceived: "06/05/25",
    salesPersonnel: "MLB",
    systemDiagram: "M.GIGANTE",
    eBoqDate: "06/05/25",
    structuralBoq: " - ",
    sBoqDate: " - ",
    sirME: " - ",
    sirMJH: " - ",
    status: "WIP",
  },
  {
    id: 5,
    clientName: "PLDT SM MARIKINA",
    projectDesc: "INDOOR LED",
    dateReceived: "06/05/25",
    salesPersonnel: "JAJA",
    systemDiagram: "M.GIGANTE",
    eBoqDate: "06/05/25",
    structuralBoq: " - ",
    sBoqDate: " - ",
    sirME: " - ",
    sirMJH: " - ",
    status: "WIP",
  },
  {
    id: 6,
    clientName: "ACLA MEDSPA",
    projectDesc: "INDOOR LED",
    dateReceived: "06/05/25",
    salesPersonnel: "REBOY",
    systemDiagram: " - ",
    eBoqDate: " - ",
    structuralBoq: " - ",
    sBoqDate: " - ",
    sirME: " - ",
    sirMJH: " - ",
    status: "WIP",
  },
  {
    id: 7,
    clientName: "PRESCO",
    projectDesc: " - ",
    dateReceived: "06/05/25",
    salesPersonnel: " - ",
    systemDiagram: " - ",
    eBoqDate: " - ",
    structuralBoq: " - ",
    sBoqDate: " - ",
    sirME: "  - ",
    sirMJH: " - ",
    status: "WIP",
  },
  {
    id: 8,
    clientName: "MR MARIANO",
    projectDesc: "INDOOR LED",
    dateReceived: "06/05/25",
    salesPersonnel: "NOEL",
    systemDiagram: "M.GIGANTE",
    eBoqDate: "06/05/25",
    structuralBoq: " - ",
    sBoqDate: "06/05/25",
    sirME: " - ",
    sirMJH: " - ",
    status: "WIP",
  },
  {
    id: 9,
    clientName: "SM EAST",
    projectDesc: "REV INDOOR",
    dateReceived: "06/09/25",
    salesPersonnel: "JAJA",
    systemDiagram: "M.GIGANTE",
    eBoqDate: "06/09/25",
    structuralBoq: "J.COLA",
    sBoqDate: "06/09/25",
    sirME: " - ",
    sirMJH: " - ",
    status: "Ongoing",
  },
  {
    id: 10,
    clientName: "UPTOWN SHOWROOM",
    projectDesc: "ADDITIONAL AUDIO",
    dateReceived: "05/29/25",
    salesPersonnel: "MLB",
    systemDiagram: "B.TOPACIO",
    eBoqDate: "05/29/25",
    structuralBoq: " - ",
    sBoqDate: " - ",
    sirME: "05/29/25",
    sirMJH: "06/05/25",
    status: "Finished",
  },
  {
    id: 11,
    clientName: "PENSHOPPE MOA",
    projectDesc: "INDOOR LED",
    dateReceived: "05/29/25",
    salesPersonnel: "KENNETH",
    systemDiagram: "M.GIGANTE",
    eBoqDate: "05/30/25",
    structuralBoq: "J. ARDINEL",
    sBoqDate: "5/30/25",
    sirME: "06/04/25",
    sirMJH: "06/05/25",
    status: "Finished",
  },
  {
    id: 12,
    clientName: "IEE SUBWAY",
    projectDesc: "OUTDOOR LED",
    dateReceived: "05/28/25",
    salesPersonnel: "KENNETH",
    systemDiagram: "J.CAMERO",
    eBoqDate: "05/30/25",
    structuralBoq: "J.COLA",
    sBoqDate: "06/04/25",
    sirME: "06/05/25",
    sirMJH: "06/05/25",
    status: "Finished",
  },
];

export const users = [
  {
    id: 1,
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Zoey Lang",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "Jane Fisher",
    role: "Senior Developer",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "William Howard",
    role: "Community Manager",
    team: "Marketing",
    status: "vacation",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    name: "Kristen Copper",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 10,
    name: "Kristen Copper",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 8,
    name: "Jane Fisher",
    role: "Senior Developer",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 7,
    name: "Zoey Lang",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },

  {
    id: 9,
    name: "William Howard",
    role: "Community Manager",
    team: "Marketing",
    status: "vacation",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 11,
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 12,
    name: "Kristen Copper",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 13,
    name: "Jane Fisher",
    role: "Senior Developer",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 14,
    name: "Zoey Lang",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 15,
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 16,
    name: "Kristen Copper",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
];
